name: deploy-stage
on:
    push:
        branches:
            - staging
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  known_hosts: unnecessary

            - name: Adding Known Hosts
              run: ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

            - name: Deploy with rsync
              run: rsync -avz --exclude={.*,*lock,*~,phpcs.xml.dist,postcss.config.js,webpack.*.js,.*/,node_modules/} --delete ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/redkeyclub/redkeyclub.com/wp-content/plugins/site-functionality
